### ISSUE TITLE
Crear vista de informacion del sistema

### ISSUE THREAD

**Issue by luprz** [SliceDevelopers/keppler_core#296]
## Objetivos:
* Mostrar fecha de lanzamiento
* Mostrar version de keppler, rails y dependencias
* Redes sociales, empresa desarrolladora

**Comment by paolavrgs** [comment]
Preview: 

![image](https://user-images.githubusercontent.com/25708355/45571696-16cb4d80-b835-11e8-9d04-6480d5592b81.png)
